name: PR Title Spell Check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install spell-checking tool
        run: npm install --global markdown-spellcheck

      - name: Check PR title spelling
        run: |
          PR_TITLE=$(git log --format=%B -n 1 "$GITHUB_SHA" | head -n 1)
          echo "PR Title: $PR_TITLE"
          echo "$PR_TITLE" | markdown-spellcheck --ignore-numbers --ignore-acronyms
