name: Spelling Check
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  spelling-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CodeQL
        uses: github/codeql-action/init@v1

      - name: Spell Check
        run: |
          export PATH="/usr/lib/hunspell:$PATH"
          misspelled_words=$(echo "${{ github.event.pull_request.title }}" | hunspell -d en_US -l)
          if [[ $misspelled_words ]]; then
            echo "Spelling errors found in the pull request title:"
            echo "$misspelled_words"
            exit 1
          fi
